[package]
name = "ctp"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
lazy_static = { version = "1.4"} 
regex = { version = "1.9" }

bindgen = { version = "0.68" }
cc = { version = "1.0", features = ["parallel"] }
